LOCATION_MAPPING = {
    [0x238000] = {"@The Great Sea/Outset Island/Underneath Link's House"},
    [0x238001] = {"@The Great Sea/Outset Island/Mesa the Grasscutter's House"},
    [0x238002] = {"@The Great Sea/Outset Island/Orca - Give 10 Knight's Crests"},
    [0x238005] = {"@The Great Sea/Outset Island/Jabun's Cave"},
    [0x238006] = {"@The Great Sea/Outset Island/Dig up Black Soil"},
    [0x238007] = {"@The Great Sea/Outset Island/Savage Labyrinth - Floor 30"},
    [0x238008] = {"@The Great Sea/Outset Island/Savage Labyrinth - Floor 50"},

    [0x238009] = {"@The Great Sea/Windfall Island/Jail - Tingle - First Gift"},
    [0x238010] = {"@The Great Sea/Windfall Island/Jail - Tingle - Second Gift"},
    [0x238011] = {"@The Great Sea/Windfall Island/Jail - Maze Chest"},
    [0x238012] = {"@The Great Sea/Windfall Island/Chu Jelly Juice Shop - Give 15 Green Chu Jelly"},
    [0x238013] = {"@The Great Sea/Windfall Island/Chu Jelly Juice Shop - Give 15 Blue Chu Jelly"},
    [0x238019] = {"@The Great Sea/Windfall Island/Lenzo's House - Left Chest"},
    [0x238020] = {"@The Great Sea/Windfall Island/Lenzo's House - Right Chest"},
    [0x238023] = {"@The Great Sea/Windfall Island/House of Wealth Chest"},
    [0x238028] = {"@The Great Sea/Windfall Island/Kreeb - Light Up Lighthouse"},
    [0x238029] = {"@The Great Sea/Windfall Island/Transparent Chest"},
    [0x238031] = {"@The Great Sea/Windfall Island/Pirate Ship"},
    [0x238043] = {"@The Great Sea/Windfall Island/Battlesquid - First Prize"},
    [0x238044] = {"@The Great Sea/Windfall Island/Battlesquid - Second Prize"},
    [0x238045] = {"@The Great Sea/Windfall Island/Battlesquid - Under 20 Shots Prize"},

    [0x238050] = {"@The Great Sea/Dragon Roost Island/Wind Shrine"},
    [0x238052] = {"@The Great Sea/Dragon Roost Island/Chest on Top of Boulder"},
    [0x238053] = {"@The Great Sea/Dragon Roost Island/Fly Across Platforms Around Island"},
    [0x238054] = {"@The Great Sea/Dragon Roost Island/Rito Aerie - Mail Sorting"},
    [0x238055] = {"@The Great Sea/Dragon Roost Island/Secret Cave"},

    [0x238056] = {"@The Great Sea/Dragon Roost Cavern/First Room"},
    [0x238057] = {"@The Great Sea/Dragon Roost Cavern/Alcove With Water Jugs"},
    [0x238058] = {"@The Great Sea/Dragon Roost Cavern/Water Jug on Upper Shelf"},
    [0x238059] = {"@The Great Sea/Dragon Roost Cavern/Boarded Up Chest"},
    [0x238060] = {"@The Great Sea/Dragon Roost Cavern/Chest Across Lava Pit"},
    [0x238061] = {"@The Great Sea/Dragon Roost Cavern/Rat Room"},
    [0x238062] = {"@The Great Sea/Dragon Roost Cavern/Rat Room Boarded Up Chest"},
    [0x238063] = {"@The Great Sea/Dragon Roost Cavern/Bird's Nest"},
    [0x238064] = {"@The Great Sea/Dragon Roost Cavern/Dark Room"},
    [0x238065] = {"@The Great Sea/Dragon Roost Cavern/Tingle Chest in Hub Room"},
    [0x238066] = {"@The Great Sea/Dragon Roost Cavern/Pot on Upper Shelf in Pot Room"},
    [0x238067] = {"@The Great Sea/Dragon Roost Cavern/Pot Room Chest"},
    [0x238068] = {"@The Great Sea/Dragon Roost Cavern/Miniboss"},
    [0x238069] = {"@The Great Sea/Dragon Roost Cavern/Under Rope Bridge"},
    [0x238070] = {"@The Great Sea/Dragon Roost Cavern/Tingle Statue Chest"},
    [0x238071] = {"@The Great Sea/Dragon Roost Cavern/Big Key Chest"},
    [0x238072] = {"@The Great Sea/Dragon Roost Cavern/Boss Stairs Left Chest"},
    [0x238073] = {"@The Great Sea/Dragon Roost Cavern/Boss Stairs Right Chest"},
    [0x238074] = {"@The Great Sea/Dragon Roost Cavern/Boss Stairs Right Pot"},
    [0x238075] = {"@The Great Sea/Dragon Roost Cavern/Gohma Heart Container"},

    [0x238076] = {"@The Great Sea/Forest Haven/On Tree Branch"},
    [0x238077] = {"@The Great Sea/Forest Haven/Small Island Chest"},

    
    [0x238072] = {"@The Great Sea/Forsaken Fortress/Phantom Ganon"},
    [0x238073] = {"@The Great Sea/Forsaken Fortress/Chest Outside Upper Jail Cell"},
    [0x238074] = {"@The Great Sea/Forsaken Fortress/Chest Inside Lower Jail Cell"},
    [0x238075] = {"@The Great Sea/Forsaken Fortress/Chest Guarded by Bokoblin"},
    [0x238076] = {"@The Great Sea/Forsaken Fortress/Chest on Bed"},
    [0x238077] = {"@The Great Sea/Forsaken Fortress/Helmaroc King Heart Container"},

    [0x2380FA] = {"@The Great Sea/Star Island/Lookout Platform"},
    [0x2380F9] = {"@The Great Sea/Star Island/Cave"},

    [0x2380DC] = {"@The Great Sea/Northern Fairy Island/Submarine"},

    [0x238094] = {"@The Great Sea/Wind Temple/Chest Between Two Dirt Patches"},
    [0x238095] = {"@The Great Sea/Wind Temple/Behind Stone Head in Hidden Upper Room"},
    [0x238096] = {"@The Great Sea/Wind Temple/Tingle Statue Chest"},
    [0x238097] = {"@The Great Sea/Wind Temple/Chest Behind Stone Head"},
    [0x238098] = {"@The Great Sea/Wind Temple/Chest in Left Alcove"},
    [0x238099] = {"@The Great Sea/Wind Temple/Big Key Chest"},
    [0x23809A] = {"@The Great Sea/Wind Temple/Chest In Many Cyclones Room"},
    [0x23809B] = {"@The Great Sea/Wind Temple/Behind Stone Head in Many Cyclones Room"},
    [0x23809C] = {"@The Great Sea/Wind Temple/Chest In Middle Of Hub Room"},
    [0x23809D] = {"@The Great Sea/Wind Temple/Spike Wall Room - First Chest"},
    [0x23809E] = {"@The Great Sea/Wind Temple/Spike Wall Room - Destroy All Cracked Floors"},
    [0x23809F] = {"@The Great Sea/Wind Temple/Wizzrobe Miniboss Room"},
    [0x2380A0] = {"@The Great Sea/Wind Temple/Chest at Top of Hub Room"},
    [0x2380A1] = {"@The Great Sea/Wind Temple/Chest Behind Seven Armos"},
    [0x2380A2] = {"@The Great Sea/Wind Temple/Kill All Enemies in Tall Basement Room"},
    [0x2380A3] = {"@The Great Sea/Wind Temple/Molgera Heart Container"},

    [0x2380F1] = {"@The Great Sea/Crescent Moon Island/Chest"},
    [0x2380F2] = {"@The Great Sea/Crescent Moon Island/Submarine"},

    [0x2380FF] = {"@The Great Sea/Seven-Star Isles/Center Platform"},
    [0x238100] = {"@The Great Sea/Seven-Star Isles/Northern Platform"},
    [0x238101] = {"@The Great Sea/Seven-Star Isles/Southern Platform"},

    [0x2380C9] = {"@The Great Sea/Overlook Island/Cave"},

    [0x238109] = {"@The Great Sea/Four-Eye Reef/Destroy the Cannons and Gunboats"},

    [0x238078] = {"@The Great Sea/Mother and Child Isles/Inside Mother Isle"},

    [0x2380CB] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Chest"},
    [0x2380CC] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Behind Left Boulder"},
    [0x2380CD] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Behind Right Boulder"},
    [0x2380CE] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Scale the Wall"},
    [0x2380CF] = {"@The Great Sea/Pawprint Isle/Wizzrobe Cave"},
    [0x2380D0] = {"@The Great Sea/Pawprint Isle/Enemy Platform"},

    [0x2380F8] = {"@The Great Sea/Flight Control Platform/Submarine"},

    [0x2380D7] = {"@The Great Sea/Western Fairy Island/Lookout Platform"},

    [0x2380E5] = {"@The Great Sea/Rock Spire Isle/Cave"},
    [0x2380E6] = {"@The Great Sea/Rock Spire Isle/Beedle's Special Shop Ship - 500 Item"},
    [0x2380E7] = {"@The Great Sea/Rock Spire Isle/Beedle's Special Shop Ship - 900 Item"},
    [0x2380E8] = {"@The Great Sea/Rock Spire Isle/Beedle's Special Shop Ship - 950 Item"},
    [0x2380E9] = {"@The Great Sea/Rock Spire Isle/Western Lookout Platform - Destroy the Cannons"},
    [0x2380EA] = {"@The Great Sea/Rock Spire Isle/Eastern Lookout Platform - Destroy the Cannons"},
    [0x2380EB] = {"@The Great Sea/Rock Spire Isle/Center Lookout Platform"},

    [0x2380D5] = {"@The Great Sea/Eastern Fairy Island/Lookout Platform - Defeat the Cannons and Enemies"},

    [0x238079] = {"@The Great Sea/Fire Mountain/Cave - Chest"},
    [0x23807A] = {"@The Great Sea/Fire Mountain/Lookout Platform Chest"},
    [0x23807B] = {"@The Great Sea/Fire Mountain/Lookout Platform - Destroy the Cannons"},

    [0x2380FB] = {"@The Great Sea/Star Belt Archipelago/Lookout Platform"},

    [0x238108] = {"@The Great Sea/Three-Eye Reef/Destroy the Cannons and Gunboats"},

    [0x238060] = {"@The Great Sea/Greatfish Isle/Hidden Chest"},

    [0x238103] = {"@The Great Sea/Cyclops Reef/Destroy the Cannons and Gunboats"},
    [0x238104] = {"@The Great Sea/Cyclops Reef/Lookout Platform - Defeat the Enemies"},

    [0x23810C] = {"@The Great Sea/Six-Eye Reef/Destroy the Cannons and Gunboats"},
    [0x23810D] = {"@The Great Sea/Six-Eye Reef/Lookout Platform - Destroy the Cannons"},
    [0x23810E] = {"@The Great Sea/Six-Eye Reef/Submarine"},

    [0x238061] = {"@The Great Sea/Tower of the Gods/Chest Behind Bombable Walls"},
    [0x238062] = {"@The Great Sea/Tower of the Gods/Pot Behind Bombable Walls"},    
    [0x238063] = {"@The Great Sea/Tower of the Gods/Hop Across Floating Boxes"},
    [0x238064] = {"@The Great Sea/Tower of the Gods/Light Two Torches"},
    [0x238065] = {"@The Great Sea/Tower of the Gods/Skulls Room Chest"},
    [0x238066] = {"@The Great Sea/Tower of the Gods/Shoot Eye Above Skulls Room Chest"},
    [0x238067] = {"@The Great Sea/Tower of the Gods/Tingle Statue Chest"},
    [0x238068] = {"@The Great Sea/Tower of the Gods/First Chest Guarded by Armos Knights"},
    [0x238069] = {"@The Great Sea/Tower of the Gods/Stone Tablet"},
    [0x23806A] = {"@The Great Sea/Tower of the Gods/Darknut Miniboss Room"},
    [0x23806B] = {"@The Great Sea/Tower of the Gods/Second Chest Guarded by Armos Knights"},
    [0x23806C] = {"@The Great Sea/Tower of the Gods/Floating Platforms Room"},
    [0x23806D] = {"@The Great Sea/Tower of the Gods/Top of Floating Platforms Room"},
    [0x23806E] = {"@The Great Sea/Tower of the Gods/Eastern Pot in Big Key Chest Room"},
    [0x23806F] = {"@The Great Sea/Tower of the Gods/Big Key Chest"},
    [0x238070] = {"@The Great Sea/Tower of the Gods/Gohdan Heart Container"},

    [0x238071] = {"@The Great Sea/Hyrule/Master Sword Chamber"},
    [0x2380A4] = {"@The Great Sea/Hyrule/Ganon's Tower - Maze Chest"},

    [0x2380D2] = {"@The Great Sea/Thorned Fairy Island/Northeastern Lookout Platform - Destroy the Cannons"},
    [0x2380D3] = {"@The Great Sea/Thorned Fairy Island/Southwestern Lookout Platform - Defeat the Enemies"},

    [0x2380BD] = {"@The Great Sea/Needle Rock Isle/Chest"},
    [0x2380BE] = {"@The Great Sea/Needle Rock Isle/Cave"},

    [0x2380C7] = {"@The Great Sea/Islet of Steel/Interior"},
    [0x2380C8] = {"@The Great Sea/Islet of Steel/Lookout Platform - Defeat the Enemies"},

    [0x2380C4] = {"@The Great Sea/Stone Watcher Island/Cave"},
    [0x2380C5] = {"@The Great Sea/Stone Watcher Island/Lookout Platform Chest"},
    [0x2380C6] = {"@The Great Sea/Stone Watcher Island/Lookout Platform - Destroy the Cannons"},

    [0x2380B7] = {"@The Great Sea/Private Oasis/Chest at Top of Waterfall"},
    [0x2380B8] = {"@The Great Sea/Private Oasis/Cabana Labyrinth - Lower Floor Chest"},
    [0x2380B9] = {"@The Great Sea/Private Oasis/Cabana Labyrinth - Upper Floor Chest"},

    [0x2380E2] = {"@The Great Sea/Bomb Island/Cave"},
    [0x2380E3] = {"@The Great Sea/Bomb Island/Lookout Platform - Defeat the Enemies"},
    [0x2380E4] = {"@The Great Sea/Bomb Island/Submarine"},

    [0x2380CA] = {"@The Great Sea/Bird's Peak Rock/Cave"},

    [0x2380DF] = {"@The Great Sea/Diamond Steppe Island/Warp Maze Cave - First Chest"},
    [0x2380E0] = {"@The Great Sea/Diamond Steppe Island/Warp Maze Cave - Second Chest"},

    [0x23810A] = {"@The Great Sea/Five-Eye Reef/Destroy the Cannons"},
    [0x23810B] = {"@The Great Sea/Five-Eye Reef/Lookout Platform"},

    [0x2380ED] = {"@The Great Sea/Shark Island/Cave"},

    [0x2380D9] = {"@The Great Sea/Southern Fairy Island/Lookout Platform - Destroy the Northwest Cannons"},
    [0x2380DA] = {"@The Great Sea/Southern Fairy Island/Lookout Platform - Destroy the Southeast Cannons"},

    [0x23807D] = {"@The Great Sea/Ice Ring Isle/Frozen Chest"},
    [0x23807E] = {"@The Great Sea/Ice Ring Isle/Cave - Chest"},
    [0x23807F] = {"@The Great Sea/Ice Ring Isle/Inner Cave - Chest"},

    [0x23804E] = {"@The Great Sea/Forbidden Woods/First Room"},
    [0x23804F] = {"@The Great Sea/Forbidden Woods/Inside Hollow Tree's Mouth"},
    [0x238050] = {"@The Great Sea/Forbidden Woods/Climb to Top Using Boko Baba Bulbs"},
    [0x238051] = {"@The Great Sea/Forbidden Woods/Pot High Above Hollow Tree"},
    [0x238052] = {"@The Great Sea/Forbidden Woods/Hole in Tree"},
    [0x238053] = {"@The Great Sea/Forbidden Woods/Morth Pit"},
    [0x238054] = {"@The Great Sea/Forbidden Woods/Vine Maze Left Chest"},
    [0x238055] = {"@The Great Sea/Forbidden Woods/Vine Maze Right Chest"},
    [0x238056] = {"@The Great Sea/Forbidden Woods/Highest Pot in Vine Maze"},
    [0x238057] = {"@The Great Sea/Forbidden Woods/Tall Room Before Miniboss"},
    [0x238058] = {"@The Great Sea/Forbidden Woods/Mothula Miniboss Room"},
    [0x238059] = {"@The Great Sea/Forbidden Woods/Past Seeds Hanging by Vines"},
    [0x23805A] = {"@The Great Sea/Forbidden Woods/Chest Across Red Hanging Flower"},
    [0x23805B] = {"@The Great Sea/Forbidden Woods/Tingle Statue Chest"},
    [0x23805C] = {"@The Great Sea/Forbidden Woods/Chest in Locked Tree Trunk"},
    [0x23805D] = {"@The Great Sea/Forbidden Woods/Big Key Chest"},
    [0x23805E] = {"@The Great Sea/Forbidden Woods/Double Mothula Room"},
    [0x23805F] = {"@The Great Sea/Forbidden Woods/Kalle Demos Heart Container"},

    [0x2380EE] = {"@The Great Sea/Cliff Plateau Isles/Cave"},
    [0x2380EF] = {"@The Great Sea/Cliff Plateau Isles/Highest Isle"},
    [0x2380F0] = {"@The Great Sea/Cliff Plateau Isles/Lookout Platform"},

    [0x238243] = {"@The Great Sea/Horseshoe Island/Play Golf"},
    [0x238244] = {"@The Great Sea/Horseshoe Island/Cave"},
    [0x238245] = {"@The Great Sea/Horseshoe Island/Northwestern Lookout Platform"},
    [0x238246] = {"@The Great Sea/Horseshoe Island/Southeastern Lookout Platform"},

    [0x2380B3] = {"@The Great Sea/Great Sea/Cyclos"},
    [0x2380B5] = {"@The Great Sea/Great Sea/Withered Trees"},
    [0x2380B6] = {"@The Great Sea/Great Sea/Ghost Ship"},

    [0x238080] = {"@The Great Sea/Headstone Island/Top of the Island"},
    [0x238081] = {"@The Great Sea/Headstone Island/Submarine"},

    [0x238082] = {"@The Great Sea/Earth Temple/Transparent Chest In Warp Pot Room"},
    [0x238083] = {"@The Great Sea/Earth Temple/Behind Curtain In Warp Pot Room"},
    [0x238084] = {"@The Great Sea/Earth Temple/Transparent Chest in First Crypt"},
    [0x238085] = {"@The Great Sea/Earth Temple/Chest Behind Destructible Walls"},
    [0x238086] = {"@The Great Sea/Earth Temple/Chest In Three Blocks Room"},
    [0x238087] = {"@The Great Sea/Earth Temple/Chest Behind Statues"},
    [0x238088] = {"@The Great Sea/Earth Temple/Casket in Second Crypt"},
    [0x238089] = {"@The Great Sea/Earth Temple/Stalfos Miniboss Room"},
    [0x23808A] = {"@The Great Sea/Earth Temple/Tingle Statue Chest"},
    [0x23808B] = {"@The Great Sea/Earth Temple/End of Foggy Room With Floormasters"},
    [0x23808C] = {"@The Great Sea/Earth Temple/Kill All Floormasters in Foggy Room"},
    [0x23808D] = {"@The Great Sea/Earth Temple/Behind Curtain Next to Hammer Button"},
    [0x23808E] = {"@The Great Sea/Earth Temple/Chest in Third Crypt"},
    [0x23808F] = {"@The Great Sea/Earth Temple/Many Mirrors Room Right Chest"},
    [0x238090] = {"@The Great Sea/Earth Temple/Many Mirrors Room Left Chest"},
    [0x238091] = {"@The Great Sea/Earth Temple/Stalfos Crypt Room"},
    [0x238092] = {"@The Great Sea/Earth Temple/Big Key Chest"},
    [0x238093] = {"@The Great Sea/Earth Temple/Jalhalla Heart Container"},

    [0x238105] = {"@The Great Sea/Two-Eye Reef/Destroy the Cannons and Gunboats"},
    [0x238106] = {"@The Great Sea/Two-Eye Reef/Lookout Platform"},
    [0x238107] = {"@The Great Sea/Two-Eye Reef/Big Octo Fairy"},

    [0x2380C0] = {"@The Great Sea/Angular Isles/Peak"},
    [0x2380C1] = {"@The Great Sea/Angular Isles/Cave"},

    [0x2380C2] = {"@The Great Sea/Boating Course/Raft"},
    [0x2380C3] = {"@The Great Sea/Boating Course/Cave"},

    [0x2380FD] = {"@The Great Sea/Five-Star Isles/Raft"},
    [0x2380FE] = {"@The Great Sea/Five-Star Isles/Submarine"},
    [0x2380FC] = {"@The Great Sea/Five-Star Isles/Lookout Platform - Destroy the Cannons"},

    [0x23812F] = {"@Treasure Salvaging/Private Oasis - Sunken Treasure"},
    [0x23811E] = {"@Treasure Salvaging/Rock Spire Isle - Sunken Treasure"},
    [0x238121] = {"@Treasure Salvaging/Eastern Fairy Isle - Sunken Treasure"},
    [0x238135] = {"@Treasure Salvaging/Southern Fairy Island - Sunken Treasure"},
    [0x23812A] = {"@Treasure Salvaging/Thorned Fairy Island - Sunken Treasure"},
    [0x238127] = {"@Treasure Salvaging/Six-Eye Reef - Sunken Treasure"},
    [0x238110] = {"@Treasure Salvaging/Star Island - Sunken Treasure"},
    [0x23811D] = {"@Treasure Salvaging/Western Fairy Island - Sunken Treasure"},
    [0x238139] = {"@Treasure Salvaging/Horseshoe Isle - Sunken Treasure"},
    [0x23811F] = {"@Treasure Salvaging/Tingle Island - Sunken Treasure"},
    [0x238113] = {"@Treasure Salvaging/Crescent Moon Island - Sunken Treasure"},
    [0x238133] = {"@Treasure Salvaging/Five-Eye Reef - Sunken Treasure"},
    [0x238115] = {"@Treasure Salvaging/Overlook Island - Sunken Treasure"},
    [0x238128] = {"@Treasure Salvaging/Tower of The Gods - Sunken Treasure"},
    [0x23813D] = {"@Treasure Salvaging/Angular isles - Sunken Treasure"},
    [0x238134] = {"@Treasure Salvaging/Shark Island - Sunken Treasure"},
    [0x238136] = {"@Treasure Salvaging/Ice Ring Isle - Sunken Treasure"},
    [0x238119] = {"@Treasure Salvaging/Windfall Island - Sunken Treasure"},
    [0x23811C] = {"@Treasure Salvaging/Flight Control Platform - Sunken Treasure"},
    [0x238130] = {"@Treasure Salvaging/Bomb Island - Sunken Treasure"},
    [0x238126] = {"@Treasure Salvaging/Cyclops Reef - Sunken Treasure"},
    [0x238118] = {"@Treasure Salvaging/Spectacle Island - Sunken Treasure"},
    [0x238132] = {"@Treasure Salvaging/Diamond Steppe Island - Sunken Treasure"},
    [0x238111] = {"@Treasure Salvaging/Northern Fairy Island - Sunken Treasure"},
    [0x23810F] = {"@Treasure Salvaging/Forsaken Fortress - Sunken Treasure"},
    [0x238120] = {"@Treasure Salvaging/Northern Triangle Isle - Sunken Treasure"},
    [0x238123] = {"@Treasure Salvaging/Star Belt Archipelago - Sunken Treasure"},
    [0x23812B] = {"@Treasure Salvaging/Needle Rock Isle - Sunken Treasure"},
    [0x238117] = {"@Treasure Salvaging/Mother & Child Isles - Sunken Treasure"},
    [0x23811A] = {"@Treasure Salvaging/Pawprint Isle - Sunken Treasure"},
    [0x238137] = {"@Treasure Salvaging/Forest Haven - Sunken Treasure"},
    [0x23813E] = {"@Treasure Salvaging/Boating Course - Sunken Treasure"},
    [0x23813F] = {"@Treasure Salvaging/Five-Star Isles - Sunken Treasure"},
    [0x238129] = {"@Treasure Salvaging/Eastern Triangle Isle - Sunken Treasure"},
    [0x23812C] = {"@Treasure Salvaging/Islet of Steel - Sunken Treasure"},
    [0x238131] = {"@Treasure Salvaging/Bird's Peak Rock - Sunken Treasure"},
    [0x238122] = {"@Treasure Salvaging/Fire Mountain - Sunken Treasure"},
    [0x238124] = {"@Treasure Salvaging/Three-Eye Reef - Sunken Treasure"},
    [0x23811B] = {"@Treasure Salvaging/Dragon Roost Mountain - Sunken Treasure"},
    [0x23813B] = {"@Treasure Salvaging/Headstone Island - Sunken Treasure"},
    [0x238109] = {"@Treasure Salvaging/Four-Eye Reef - Sunken Treasure"},
    
    [0x238125] = {"@Triforce Salvaging/Greatfish Isle - Sunken Treasure"},
    [0x238112] = {"@Triforce Salvaging/Gale Isle - Sunken Treasure"},
    [0x23812D] = {"@Triforce Salvaging/Stonewatcher Island - Sunken Treasure"},
    [0x23813A] = {"@Triforce Salvaging/Outset island - Sunken Treasure"},
    [0x238138] = {"@Triforce Salvaging/Cliff Plateau Isles - Sunken Treasure"},
    [0x23812E] = {"@Triforce Salvaging/Southern Triangle Isle - Sunken Treasure"},
    [0x238114] = {"@Triforce Salvaging/Seven-Star Isles - Sunken Treasure"},
    [0x23813C] = {"@Triforce Salvaging/Two-Eye Reef - Sunken Treasure"},
}
