LOCATION_MAPPING = {
    [0x238000] = {"@The Great Sea/Outset Island/Underneath Link's House"},
    [0x238001] = {"@The Great Sea/Outset Island/Mesa the Grasscutter's House"},
    [0x238002] = {"@The Great Sea/Outset Island/Orca - Give 10 Knight's Crests"},
    [0x238004] = {"@The Great Sea/Outset Island/Great Fairy"},
    [0x238005] = {"@The Great Sea/Outset Island/Jabun's Cave"},
    [0x238006] = {"@The Great Sea/Outset Island/Dig up Black Soil"},
    [0x238007] = {"@The Great Sea/Outset Island/Savage Labyrinth - Floor 30"},
    [0x238008] = {"@The Great Sea/Outset Island/Savage Labyrinth - Floor 50"},

    [0x238009] = {"@The Great Sea/Windfall Island - Free/Jail - Tingle - First Gift"},
    [0x23800a] = {"@The Great Sea/Windfall Island - Free/Jail - Tingle - Second Gift"},
    [0x23800b] = {"@The Great Sea/Windfall Island - Free/Jail - Maze Chest"},
    [0x23800c] = {"@The Great Sea/Windfall Island - Long Sidequests/Chu Jelly Juice Shop - Give 15 Green Chu Jelly"},
    [0x23800d] = {"@The Great Sea/Windfall Island - Long Sidequests/Chu Jelly Juice Shop - Give 15 Blue Chu Jelly"},
    [0x23800e] = {"@The Great Sea/Windfall Island - Short Sidequests/Ivan - Catch Killer Bees"},
    [0x23800f] = {"@The Great Sea/Windfall Island - Short Sidequests/Mrs. Marie - Catch Killer Bees"},
    [0x238010] = {"@The Great Sea/Windfall Island - Long Sidequests/Mrs. Marie - Give 1 Joy Pendant"},
    [0x238011] = {"@The Great Sea/Windfall Island - Long Sidequests/Mrs. Marie - Give 21 Joy Pendants"},
    [0x238012] = {"@The Great Sea/Windfall Island - Long Sidequests/Mrs. Marie - Give 40 Joy Pendants"},
    [0x238013] = {"@The Great Sea/Windfall Island - Short Sidequests/Lenzo's House - Left Chest"},
    [0x238014] = {"@The Great Sea/Windfall Island - Short Sidequests/Lenzo's House - Right Chest"},
    [0x238015] = {"@The Great Sea/Windfall Island - Long Sidequests/Lenzo's House - Become Lenzo's Assistant"},
    [0x238016] = {"@The Great Sea/Windfall Island - Long Sidequests/Lenzo's House - Bring Forest Firefly"},
    [0x238017] = {"@The Great Sea/Windfall Island - Free/House of Wealth Chest"},
    [0x238018] = {"@The Great Sea/Windfall Island - Long Sidequests/Maggie's Father - Give 20 Skull Necklaces"},
    [0x238019] = {"@The Great Sea/Windfall Island - Free/Maggie - Free Item"},
    [0x23801a] = {"@The Great Sea/Windfall Island - Short Sidequests/Maggie - Delivery Reward"},
    [0x23801b] = {"@The Great Sea/Windfall Island - Short Sidequests/Cafe Bar - Postman"},
    [0x23801c] = {"@The Great Sea/Windfall Island - Short Sidequests/Kreeb - Light Up Lighthouse"},
    [0x23801d] = {"@The Great Sea/Windfall Island - Short Sidequests/Transparent Chest"},
    [0x23801e] = {"@The Great Sea/Windfall Island - Free/Tott - Teach Rhythm"},
    [0x23801f] = {"@The Great Sea/Windfall Island - Minigames/Pirate Ship"},
    [0x238020] = {"@The Great Sea/Windfall Island - Minigames/5 Rupee Auction"},
    [0x238021] = {"@The Great Sea/Windfall Island - Minigames/40 Rupee Auction"},
    [0x238022] = {"@The Great Sea/Windfall Island - Minigames/60 Rupee Auction"},
    [0x238023] = {"@The Great Sea/Windfall Island - Minigames/80 Rupee Auction"},
    [0x238024] = {"@The Great Sea/Windfall Island - Short Sidequests/Zunari - Stock Exotic Flower in Zunari's Shop"},
    [0x238025] = {"@The Great Sea/Windfall Island - Long Sidequests/Sam - Decorate the Town"},
    [0x23802a] = {"@The Great Sea/Windfall Island - Short Sidequests/Mila - Follow the Thief"},
    [0x23802b] = {"@The Great Sea/Windfall Island - Minigames/Battlesquid - First Prize"},
    [0x23802c] = {"@The Great Sea/Windfall Island - Minigames/Battlesquid - Second Prize"},
    [0x23802d] = {"@The Great Sea/Windfall Island - Minigames/Battlesquid - Under 20 Shots Prize"},
    [0x23802e] = {"@The Great Sea/Windfall Island - Short Sidequests/Pompie and Vera - Secret Meeting Photo"},
    [0x23802f] = {"@The Great Sea/Windfall Island - Long Sidequests/Kamo - Full Moon Photo"},
    [0x238030] = {"@The Great Sea/Windfall Island - Short Sidequests/Minenco - Miss Windfall Photo"},
    [0x238031] = {"@The Great Sea/Windfall Island - Long Sidequests/Linda and Anton"},

    [0x238032] = {"@The Great Sea/Dragon Roost Island/Wind Shrine"},
    [0x238033] = {"@The Great Sea/Dragon Roost Island/Rito Aerie - Give Hoskit 20 Golden Feathers"},
    [0x238034] = {"@The Great Sea/Dragon Roost Island/Chest on Top of Boulder"},
    [0x238035] = {"@The Great Sea/Dragon Roost Island/Fly Across Platforms Around Island"},
    [0x238036] = {"@The Great Sea/Dragon Roost Island/Rito Aerie - Mail Sorting"},
    [0x238037] = {"@The Great Sea/Dragon Roost Island/Secret Cave"},

    [0x238038] = {"@Dragon Roost Cavern/First Room/"},
    [0x238039] = {"@Dragon Roost Cavern/Alcove With Water Jugs/"},
    [0x23803a] = {"@Dragon Roost Cavern/Water Jug on Upper Shelf/"},
    [0x23803b] = {"@Dragon Roost Cavern/Boarded Up Chest/"},
    [0x23803c] = {"@Dragon Roost Cavern/Chest Across Lava Pit/"},
    [0x23803d] = {"@Dragon Roost Cavern/Rat Room/"},
    [0x23803e] = {"@Dragon Roost Cavern/Rat Room Boarded Up Chest/"},
    [0x23803f] = {"@Dragon Roost Cavern/Bird's Nest/"},
    [0x238040] = {"@Dragon Roost Cavern/Dark Room/"},
    [0x238041] = {"@Dragon Roost Cavern/Tingle Statue in Hub Room/"},
    [0x238042] = {"@Dragon Roost Cavern/Pot on Upper Shelf in Pot Room/"},
    [0x238043] = {"@Dragon Roost Cavern/Pot Room Chest/"},
    [0x238044] = {"@Dragon Roost Cavern/Miniboss/"},
    [0x238045] = {"@Dragon Roost Cavern/Under Rope Bridge/"},
    [0x238046] = {"@Dragon Roost Cavern/Tingle Statue Chest/"},
    [0x238047] = {"@Dragon Roost Cavern/Big Key Chest/"},
    [0x238049] = {"@Dragon Roost Cavern/Boss Stairs Left Chest/"},
    [0x238048] = {"@Dragon Roost Cavern/Boss Stairs Right Chest/"},
    [0x23804a] = {"@Dragon Roost Cavern/Boss Stairs Right Pot/"},
    [0x23804b] = {"@Dragon Roost Cavern/Gohma Heart Container/"},

    [0x23804c] = {"@The Great Sea/Forest Haven/On Tree Branch"},
    [0x23804d] = {"@The Great Sea/Forest Haven/Small Island Chest"},

    [0x23804e] = {"@The Great Sea/Forbidden Woods/First Room"},
    [0x23804f] = {"@The Great Sea/Forbidden Woods/Inside Hollow Tree's Mouth"},
    [0x238050] = {"@The Great Sea/Forbidden Woods/Climb to Top Using Boko Baba Bulbs"},
    [0x238051] = {"@The Great Sea/Forbidden Woods/Pot High Above Hollow Tree"},
    [0x238052] = {"@The Great Sea/Forbidden Woods/Hole in Tree"},
    [0x238053] = {"@The Great Sea/Forbidden Woods/Morth Pit"},
    [0x238054] = {"@The Great Sea/Forbidden Woods/Vine Maze Left Chest"},
    [0x238055] = {"@The Great Sea/Forbidden Woods/Vine Maze Right Chest"},
    [0x238056] = {"@The Great Sea/Forbidden Woods/Highest Pot in Vine Maze"},
    [0x238057] = {"@The Great Sea/Forbidden Woods/Tall Room Before Miniboss"},
    [0x238058] = {"@The Great Sea/Forbidden Woods/Mothula Miniboss Room"},
    [0x238059] = {"@The Great Sea/Forbidden Woods/Past Seeds Hanging by Vines"},
    [0x23805a] = {"@The Great Sea/Forbidden Woods/Chest Across Red Hanging Flower"},
    [0x23805b] = {"@The Great Sea/Forbidden Woods/Tingle Statue Chest"},
    [0x23805c] = {"@The Great Sea/Forbidden Woods/Chest in Locked Tree Trunk"},
    [0x23805d] = {"@The Great Sea/Forbidden Woods/Big Key Chest"},
    [0x23805e] = {"@The Great Sea/Forbidden Woods/Double Mothula Room"},
    [0x23805f] = {"@The Great Sea/Forbidden Woods/Kalle Demos Heart Container"},

    [0x238060] = {"@The Great Sea/Greatfish Isle/Hidden Chest"},

    [0x238061] = {"@Tower of the Gods/Chest Behind Bombable Walls/"},
    [0x238062] = {"@Tower of the Gods/Pot Behind Bombable Walls/"},
    [0x238063] = {"@Tower of the Gods/Hop Across Floating Boxes/"},
    [0x238064] = {"@Tower of the Gods/Light Two Torches/"},
    [0x238065] = {"@Tower of the Gods/Skulls Room Chest/"},
    [0x238066] = {"@Tower of the Gods/Shoot Eye Above Skulls Room Chest/"},
    [0x238067] = {"@Tower of the Gods/Tingle Statue Chest/"},
    [0x238068] = {"@Tower of the Gods/First Chest Guarded by Armos Knights/"},
    [0x238069] = {"@Tower of the Gods/Stone Tablet/"},
    [0x23806a] = {"@Tower of the Gods/Darknut Miniboss Room/"},
    [0x23806b] = {"@Tower of the Gods/Second Chest Guarded by Armos Knights/"},
    [0x23806c] = {"@Tower of the Gods/Floating Platforms Room/"},
    [0x23806d] = {"@Tower of the Gods/Top of Floating Platforms Room/"},
    [0x23806e] = {"@Tower of the Gods/Eastern Pot in Big Key Chest Room/"},
    [0x23806f] = {"@Tower of the Gods/Big Key Chest/"},
    [0x238070] = {"@Tower of the Gods/Gohdan Heart Container/"},

    [0x238071] = {"@The Great Sea/Hyrule/Master Sword Chamber"},
    [0x2380a4] = {"@The Great Sea/Hyrule/Ganon's Tower - Maze Chest"},
    
    [0x2380a5] = {"@The Great Sea/Mailbox/Letter from Hoskit's Girlfriend"},
    [0x2380a6] = {"@The Great Sea/Mailbox/Letter from Baito's Mother"},
    [0x2380a7] = {"@The Great Sea/Mailbox/Letter from Baito"},
    [0x2380a8] = {"@The Great Sea/Mailbox/Letter from Komali's Father"},
    [0x2380a9] = {"@The Great Sea/Mailbox/Letter Advertising Bombs in Beedle's Shop"},
    [0x2380aa] = {"@The Great Sea/Mailbox/Letter Advertising Rock Spire Shop Ship"},
    [0x2380ad] = {"@The Great Sea/Mailbox/Letter from Orca"},
    [0x2380ae] = {"@The Great Sea/Mailbox/Letter from Grandma"},
    [0x2380af] = {"@The Great Sea/Mailbox/Letter from Aryll"},
    [0x2380b0] = {"@The Great Sea/Mailbox/Letter from Tingle"},

    [0x238072] = {"@Forsaken Fortress/Phantom Ganon/"},
    [0x238073] = {"@Forsaken Fortress/Chest Outside Upper Jail Cell/"},
    [0x238074] = {"@Forsaken Fortress/Chest Inside Lower Jail Cell/"},
    [0x238075] = {"@Forsaken Fortress/Chest Guarded by Bokoblin/"},
    [0x238076] = {"@Forsaken Fortress/Chest on Bed/"},
    [0x238077] = {"@Forsaken Fortress/Helmaroc King Heart Container/"},

    [0x238078] = {"@The Great Sea/Mother and Child Isles/Inside Mother Isle"},

    [0x238079] = {"@The Great Sea/Fire Mountain/Cave - Chest"},
    [0x23807a] = {"@The Great Sea/Fire Mountain/Lookout Platform Chest"},
    [0x23807b] = {"@The Great Sea/Fire Mountain/Lookout Platform - Destroy the Cannons"},
    [0x23807c] = {"@The Great Sea/Fire Mountain/Big Octo"},

    [0x23807d] = {"@The Great Sea/Ice Ring Isle/Frozen Chest"},
    [0x23807e] = {"@The Great Sea/Ice Ring Isle/Cave - Chest"},
    [0x23807f] = {"@The Great Sea/Ice Ring Isle/Inner Cave - Chest"},

    [0x238080] = {"@The Great Sea/Headstone Island/Top of the Island"},
    [0x238081] = {"@The Great Sea/Headstone Island/Submarine"},

    [0x238082] = {"@The Great Sea/Earth Temple/Transparent Chest In Warp Pot Room"},
    [0x238083] = {"@The Great Sea/Earth Temple/Behind Curtain In Warp Pot Room"},
    [0x238084] = {"@The Great Sea/Earth Temple/Transparent Chest in First Crypt"},
    [0x238085] = {"@The Great Sea/Earth Temple/Chest Behind Destructible Walls"},
    [0x238086] = {"@The Great Sea/Earth Temple/Chest In Three Blocks Room"},
    [0x238087] = {"@The Great Sea/Earth Temple/Chest Behind Statues"},
    [0x238088] = {"@The Great Sea/Earth Temple/Casket in Second Crypt"},
    [0x238089] = {"@The Great Sea/Earth Temple/Stalfos Miniboss Room"},
    [0x23808a] = {"@The Great Sea/Earth Temple/Tingle Statue Chest"},
    [0x23808b] = {"@The Great Sea/Earth Temple/End of Foggy Room With Floormasters"},
    [0x23808c] = {"@The Great Sea/Earth Temple/Kill All Floormasters in Foggy Room"},
    [0x23808d] = {"@The Great Sea/Earth Temple/Behind Curtain Next to Hammer Button"},
    [0x23808e] = {"@The Great Sea/Earth Temple/Chest in Third Crypt"},
    [0x23808f] = {"@The Great Sea/Earth Temple/Many Mirrors Room Right Chest"},
    [0x238090] = {"@The Great Sea/Earth Temple/Many Mirrors Room Left Chest"},
    [0x238091] = {"@The Great Sea/Earth Temple/Stalfos Crypt Room"},
    [0x238092] = {"@The Great Sea/Earth Temple/Big Key Chest"},
    [0x238093] = {"@The Great Sea/Earth Temple/Jalhalla Heart Container"},

    [0x238094] = {"@Wind Temple/Chest Between Two Dirt Patches/"},
    [0x238095] = {"@Wind Temple/Behind Stone Head in Hidden Upper Room/"},
    [0x238096] = {"@Wind Temple/Tingle Statue Chest/"},
    [0x238097] = {"@Wind Temple/Chest Behind Stone Head/"},
    [0x238098] = {"@Wind Temple/Chest in Left Alcove/"},
    [0x238099] = {"@Wind Temple/Big Key Chest/"},
    [0x23809a] = {"@Wind Temple/Chest In Many Cyclones Room/"},
    [0x23809b] = {"@Wind Temple/Behind Stone Head in Many Cyclones Room/"},
    [0x23809c] = {"@Wind Temple/Chest In Middle of Hub Room/"},
    [0x23809d] = {"@Wind Temple/Spike Wall Room - First Chest/"},
    [0x23809e] = {"@Wind Temple/Spike Wall Room - Destroy All Cracked Floors/"},
    [0x23809f] = {"@Wind Temple/Wizzrobe Miniboss Room/"},
    [0x2380a0] = {"@Wind Temple/Chest at Top of Hub Room/"},
    [0x2380a1] = {"@Wind Temple/Chest Behind Seven Armos/"},
    [0x2380a2] = {"@Wind Temple/Kill All Enemies in Tall Basement Room/"},
    [0x2380a3] = {"@Wind Temple/Molgera Heart Container/"},

    [0x2380b1] = {"@The Great Sea/Great Sea/Beedle's Shop Ship - 20 Rupee Item"},
    [0x2380b2] = {"@The Great Sea/Great Sea/Salvage Corp Gift"},
    [0x2380b3] = {"@The Great Sea/Great Sea/Cyclos"},
    [0x2380b4] = {"@The Great Sea/Great Sea/Goron Trading Reward"},
    [0x2380b5] = {"@The Great Sea/Great Sea/Withered Trees"},
    [0x2380b6] = {"@The Great Sea/Great Sea/Ghost Ship"},

    [0x2380b7] = {"@The Great Sea/Private Oasis/Chest at Top of Waterfall"},
    [0x2380b8] = {"@The Great Sea/Private Oasis/Cabana Labyrinth - Lower Floor Chest"},
    [0x2380b9] = {"@The Great Sea/Private Oasis/Cabana Labyrinth - Upper Floor Chest"},
    [0x2380ba] = {"@The Great Sea/Private Oasis/Big Octo"},
    
    [0x2380bb] = {"@The Great Sea/Spectacle Island/Spectacle Island - Barrel Shooting - First Prize"},
    [0x2380bc] = {"@The Great Sea/Spectacle Island/Spectacle Island - Barrel Shooting - Second Prize"},

    [0x2380bd] = {"@The Great Sea/Needle Rock Isle/Chest in Ring of Fire"},
    [0x2380be] = {"@The Great Sea/Needle Rock Isle/Cave"},
    [0x2380bf] = {"@The Great Sea/Needle Rock Isle/Golden Gunboat"},

    [0x2380c0] = {"@The Great Sea/Angular Isles/Peak"},
    [0x2380c1] = {"@The Great Sea/Angular Isles/Cave"},

    [0x2380c2] = {"@The Great Sea/Boating Course/Raft"},
    [0x2380c3] = {"@The Great Sea/Boating Course/Cave"},

    [0x2380c4] = {"@The Great Sea/Stone Watcher Island/Cave"},
    [0x2380c5] = {"@The Great Sea/Stone Watcher Island/Lookout Platform Chest"},
    [0x2380c6] = {"@The Great Sea/Stone Watcher Island/Lookout Platform - Destroy the Cannons"},

    [0x2380c7] = {"@The Great Sea/Islet of Steel/Interior"},
    [0x2380c8] = {"@The Great Sea/Islet of Steel/Lookout Platform - Defeat the Enemies"},

    [0x2380c9] = {"@The Great Sea/Overlook Island/Cave"},

    [0x2380ca] = {"@The Great Sea/Bird's Peak Rock/Cave"},

    [0x2380cb] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Chest"},
    [0x2380cc] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Behind Left Boulder"},
    [0x2380cd] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Behind Right Boulder"},
    [0x2380ce] = {"@The Great Sea/Pawprint Isle/Chuchu Cave - Scale the Wall"},
    [0x2380cf] = {"@The Great Sea/Pawprint Isle/Wizzrobe Cave"},
    [0x2380d0] = {"@The Great Sea/Pawprint Isle/Lookout Platform - Defeat the Enemies"},

    [0x2380d1] = {"@The Great Sea/Thorned Fairy Island/Great Fairy"},
    [0x2380d2] = {"@The Great Sea/Thorned Fairy Island/Northeastern Lookout Platform - Destroy the Cannons"},
    [0x2380d3] = {"@The Great Sea/Thorned Fairy Island/Southwestern Lookout Platform - Defeat the Enemies"},

    [0x2380d4] = {"@The Great Sea/Eastern Fairy Island/Great Fairy"},
    [0x2380d5] = {"@The Great Sea/Eastern Fairy Island/Lookout Platform - Defeat the Cannons and Enemies"},

    [0x2380d6] = {"@The Great Sea/Western Fairy Island/Great Fairy"},
    [0x2380d7] = {"@The Great Sea/Western Fairy Island/Lookout Platform"},

    [0x2380d8] = {"@The Great Sea/Southern Fairy Island/Great Fairy"},
    [0x2380d9] = {"@The Great Sea/Southern Fairy Island/Lookout Platform - Destroy the Northwest Cannons"},
    [0x2380da] = {"@The Great Sea/Southern Fairy Island/Lookout Platform - Destroy the Southeast Cannons"},

    [0x2380db] = {"@The Great Sea/Northern Fairy Island/Great Fairy"},
    [0x2380dc] = {"@The Great Sea/Northern Fairy Island/Submarine"},
    
    [0x2380dd] = {"@The Great Sea/Tingle Island/Ankle - Reward for All Tingle Statues"},
    [0x2380de] = {"@The Great Sea/Tingle Island/Big Octo"},

    [0x2380df] = {"@The Great Sea/Diamond Steppe Island/Warp Maze Cave - First Chest"},
    [0x2380e0] = {"@The Great Sea/Diamond Steppe Island/Warp Maze Cave - Second Chest"},
    [0x2380e1] = {"@The Great Sea/Diamond Steppe Island/Big Octo"},

    [0x2380e2] = {"@The Great Sea/Bomb Island/Cave"},
    [0x2380e3] = {"@The Great Sea/Bomb Island/Lookout Platform - Defeat the Enemies"},
    [0x2380e4] = {"@The Great Sea/Bomb Island/Submarine"},

    [0x2380e5] = {"@The Great Sea/Rock Spire Isle/Cave"},
    [0x2380e6] = {"@The Great Sea/Rock Spire Isle/Beedle's Special Shop Ship - 500 Item"},
    [0x2380e7] = {"@The Great Sea/Rock Spire Isle/Beedle's Special Shop Ship - 900 Item"},
    [0x2380e8] = {"@The Great Sea/Rock Spire Isle/Beedle's Special Shop Ship - 950 Item"},
    [0x2380e9] = {"@The Great Sea/Rock Spire Isle/Western Lookout Platform - Destroy the Cannons"},
    [0x2380ea] = {"@The Great Sea/Rock Spire Isle/Eastern Lookout Platform - Destroy the Cannons"},
    [0x2380eb] = {"@The Great Sea/Rock Spire Isle/Center Lookout Platform"},
    [0x2380ec] = {"@The Great Sea/Rock Spire Isle/Southeast Gunboat"},

    [0x2380ed] = {"@The Great Sea/Shark Island/Cave"},

    [0x2380ee] = {"@The Great Sea/Cliff Plateau Isles/Cave"},
    [0x2380ef] = {"@The Great Sea/Cliff Plateau Isles/Highest Isle"},
    [0x2380f0] = {"@The Great Sea/Cliff Plateau Isles/Lookout Platform"},

    [0x2380f1] = {"@The Great Sea/Crescent Moon Island/Chest"},
    [0x2380f2] = {"@The Great Sea/Crescent Moon Island/Submarine"},

    [0x2380f3] = {"@The Great Sea/Horseshoe Island/Play Golf"},
    [0x2380f4] = {"@The Great Sea/Horseshoe Island/Cave"},
    [0x2380f5] = {"@The Great Sea/Horseshoe Island/Northwestern Lookout Platform"},
    [0x2380f6] = {"@The Great Sea/Horseshoe Island/Southeastern Lookout Platform"},

    [0x2380f7] = {"@The Great Sea/Flight Control Platform/Bird-Man Contest - First Prize"},
    [0x2380f8] = {"@The Great Sea/Flight Control Platform/Submarine"},

    [0x2380fa] = {"@The Great Sea/Star Island/Lookout Platform"},
    [0x2380f9] = {"@The Great Sea/Star Island/Cave"},

    [0x2380fb] = {"@The Great Sea/Star Belt Archipelago/Lookout Platform"},

    [0x2380fd] = {"@The Great Sea/Five-Star Isles/Raft"},
    [0x2380fe] = {"@The Great Sea/Five-Star Isles/Submarine"},
    [0x2380fc] = {"@The Great Sea/Five-Star Isles/Lookout Platform - Destroy the Cannons"},

    [0x2380ff] = {"@The Great Sea/Seven-Star Isles/Center Platform"},
    [0x238100] = {"@The Great Sea/Seven-Star Isles/Northern Platform"},
    [0x238101] = {"@The Great Sea/Seven-Star Isles/Southern Platform"},
    [0x238102] = {"@The Great Sea/Seven-Star Isles/Big Octo"},

    [0x238103] = {"@The Great Sea/Cyclops Reef/Destroy the Cannons and Gunboats"},
    [0x238104] = {"@The Great Sea/Cyclops Reef/Lookout Platform - Defeat the Enemies"},

    [0x238105] = {"@The Great Sea/Two-Eye Reef/Destroy the Cannons and Gunboats"},
    [0x238106] = {"@The Great Sea/Two-Eye Reef/Lookout Platform"},
    [0x238107] = {"@The Great Sea/Two-Eye Reef/Big Octo Great Fairy"},

    [0x238108] = {"@The Great Sea/Three-Eye Reef/Destroy the Cannons and Gunboats"},

    [0x238109] = {"@The Great Sea/Four-Eye Reef/Destroy the Cannons and Gunboats"},

    [0x23810a] = {"@The Great Sea/Five-Eye Reef/Destroy the Cannons"},
    [0x23810b] = {"@The Great Sea/Five-Eye Reef/Lookout Platform"},

    [0x23810c] = {"@The Great Sea/Six-Eye Reef/Destroy the Cannons and Gunboats"},
    [0x23810d] = {"@The Great Sea/Six-Eye Reef/Lookout Platform - Destroy the Cannons"},
    [0x23810e] = {"@The Great Sea/Six-Eye Reef/Submarine"},

    [0x23810f] = {"@Treasure Salvaging/Forsaken Fortress Sector - Sunken Treasure 25/Salvage"},
    [0x238110] = {"@Treasure Salvaging/Star Island - Sunken Treasure 7/Salvage"},
    [0x238111] = {"@Treasure Salvaging/Northern Fairy Island - Sunken Treasure 24/Salvage"},
    [0x238113] = {"@Treasure Salvaging/Crescent Moon Island - Sunken Treasure 11/Salvage"},
    [0x238115] = {"@Treasure Salvaging/Overlook Island - Sunken Treasure 13/Salvage"},
    [0x238116] = {"@Treasure Salvaging/Four-Eye Reef - Sunken Treasure 41/Salvage"},
    [0x238117] = {"@Treasure Salvaging/Mother and Child Isles - Sunken Treasure 29/Salvage"},
    [0x238118] = {"@Treasure Salvaging/Spectacle Island - Sunken Treasure 22/Salvage"},
    [0x238119] = {"@Treasure Salvaging/Windfall Island - Sunken Treasure 18/Salvage"},
    [0x23811a] = {"@Treasure Salvaging/Pawprint Isle - Sunken Treasure 30/Salvage"},
    [0x23811b] = {"@Treasure Salvaging/Dragon Roost Island - Sunken Treasure 39/Salvage"},
    [0x23811c] = {"@Treasure Salvaging/Flight Control Platform - Sunken Treasure 19/Salvage"},
    [0x23811d] = {"@Treasure Salvaging/Western Fairy Island - Sunken Treasure 8/Salvage"},
    [0x23811e] = {"@Treasure Salvaging/Rock Spire Isle - Sunken Treasure 2/Salvage"},
    [0x23811f] = {"@Treasure Salvaging/Tingle Island - Sunken Treasure 10/Salvage"},
    [0x238120] = {"@Treasure Salvaging/Northern Triangle Island - Sunken Treasure 26/Salvage"},
    [0x238121] = {"@Treasure Salvaging/Eastern Fairy Island - Sunken Treasure 3/Salvage"},
    [0x238122] = {"@Treasure Salvaging/Fire Mountain - Sunken Treasure 37/Salvage"},
    [0x238123] = {"@Treasure Salvaging/Star Belt Archipelago - Sunken Treasure 27/Salvage"},
    [0x238124] = {"@Treasure Salvaging/Three-Eye Reef - Sunken Treasure 38/Salvage"},
    [0x238126] = {"@Treasure Salvaging/Cyclops Reef - Sunken Treasure 21/Salvage"},
    [0x238127] = {"@Treasure Salvaging/Six-Eye Reef - Sunken Treasure 6/Salvage"},
    [0x238128] = {"@Treasure Salvaging/Tower of The Gods Sector - Sunken Treasure 14/Salvage"},
    [0x238129] = {"@Treasure Salvaging/Eastern Triangle Island - Sunken Treasure 34/Salvage"},
    [0x23812a] = {"@Treasure Salvaging/Thorned Fairy Island - Sunken Treasure 5/Salvage"},
    [0x23812b] = {"@Treasure Salvaging/Needle Rock Isle - Sunken Treasure 28/Salvage"},
    [0x23812c] = {"@Treasure Salvaging/Islet of Steel - Sunken Treasure 35/Salvage"},
    [0x23812f] = {"@Treasure Salvaging/Private Oasis - Sunken Treasure 1/Salvage"},
    [0x238130] = {"@Treasure Salvaging/Bomb Island - Sunken Treasure 20/Salvage"},
    [0x238131] = {"@Treasure Salvaging/Bird's Peak Rock - Sunken Treasure 36/Salvage"},
    [0x238132] = {"@Treasure Salvaging/Diamond Steppe Island - Sunken Treasure 23/Salvage"},
    [0x238133] = {"@Treasure Salvaging/Five-Eye Reef - Sunken Treasure 12/Salvage"},
    [0x238134] = {"@Treasure Salvaging/Shark Island - Sunken Treasure 16/Salvage"},
    [0x238135] = {"@Treasure Salvaging/Southern Fairy Island - Sunken Treasure 4/Salvage"},
    [0x238136] = {"@Treasure Salvaging/Ice Ring Isle - Sunken Treasure 17/Salvage"},
    [0x238137] = {"@Treasure Salvaging/Forest Haven - Sunken Treasure 31/Salvage"},
    [0x238139] = {"@Treasure Salvaging/Horseshoe Island - Sunken Treasure 9/Salvage"},
    [0x23813b] = {"@Treasure Salvaging/Headstone Island - Sunken Treasure 40/Salvage"},
    [0x23813d] = {"@Treasure Salvaging/Angular Isles - Sunken Treasure 15/Salvage"},
    [0x23813e] = {"@Treasure Salvaging/Boating Course - Sunken Treasure 32/Salvage"},
    [0x23813f] = {"@Treasure Salvaging/Five-Star Isles - Sunken Treasure 33/Salvage"},

    [0x238112] = {"@Triforce Salvaging/Gale Isle - Sunken Triforce 2/Salvage"},
    [0x238114] = {"@Triforce Salvaging/Seven-Star Isles - Sunken Triforce 7/Salvage"},
    [0x238125] = {"@Triforce Salvaging/Greatfish Isle - Sunken Triforce 1/Salvage"},
    [0x23812d] = {"@Triforce Salvaging/Stone Watcher Island - Sunken Triforce 3/Salvage"},
    [0x23812e] = {"@Triforce Salvaging/Southern Triangle Island - Sunken Triforce 6/Salvage"},
    [0x238138] = {"@Triforce Salvaging/Cliff Plateau Isles - Sunken Triforce 5/Salvage"},
    [0x23813a] = {"@Triforce Salvaging/Outset island - Sunken Triforce 4/Salvage"},
    [0x23813c] = {"@Triforce Salvaging/Two-Eye Reef - Sunken Triforce 8/Salvage"},
}
